import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav className='nav-bar'>
          <img />
          <a href='/home' className='home-link'>Home</a>
          <a href='/events' className='events-link'>Events</a>
          <a href='/about-us' className='about-link'>About us</a>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map(ev => <a key={ev.id} href={`/events/${ev.id}`}> 
        <Image width={200} height={100} alt={ev.title} src={ev.image}/>
        <h2>{ev.title}</h2> 
        <p>{ev.description}</p> </a>)}
      </main>

      <footer className={styles.footer}>
        <p>Victor Woydowski Dralle, All Rights Reserved ©</p>
      </footer>
    </>
  )
}

export async function getServerSideProps() {
  const {events_categories} = await import('/data/data.json');

  return {
      props:{
          data:events_categories,

      },
  };
}